version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-libro
    environment:
      POSTGRES_USER: nityashukla
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: libro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: libro-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://nityashukla:password123@db:5432/libro_db
      ENABLE_BORROW: "True"
      ENABLE_RETURN: "True"
      ENABLE_BOOKS: "True"
      ENABLE_USERS: "True"
      ENABLE_CACHE: "True"
      DEBUG: "True"
      API_RATE_LIMIT: "100"

volumes:
  postgres_data: